language: objective-c
osx_image: xcode8.2

script:
- set -o pipefail
- xcodebuild clean build test -workspace ./Chatto.xcworkspace -scheme Chatto -sdk iphonesimulator10.2 -destination 'platform=iOS Simulator,name=iPhone 7' -configuration Debug | xcpretty
- bash <(curl -s https://codecov.io/bash) -J 'Chatto'
- xcodebuild clean build test -workspace ./Chatto.xcworkspace -scheme ChattoAdditions -sdk iphonesimulator10.2 -destination 'platform=iOS Simulator,name=iPhone 7' -configuration Debug | xcpretty
- bash <(curl -s https://codecov.io/bash) -J 'ChattoAdditions'
- xcodebuild clean build test -workspace ./ChattoApp/ChattoApp.xcworkspace -scheme ChattoApp -sdk iphonesimulator10.2 -destination 'platform=iOS Simulator,name=iPhone 7' -configuration Debug | xcpretty
